export const FETCH_SENTENCES = 'FETCH_SENTENCES';
export const FETCH_SENTENCES_SUCCESS = 'FETCH_SENTENCES_SUCCESS';
export const FETCH_SENTENCES_ERROR = 'FETCH_SENTENCES_ERROR';
export const CLEAR_SENTENCES = 'CLEAR_SENTENCES';
