// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fontFamily': string;
  'fontSize': string;
  'fontWeight': string;
  'onPrimary': string;
  'primary': string;
}
export const cssExports: CssExports;
export default cssExports;
